https://github.com/blockscout/blockscout/actions/runs/5609619657/job/15197599418#step:4:1
name: Proof of ownership for this repo is the author of this article that has been published by josephparente204@gmail.com 

on:
  push:
    branches: [ "smart-contract-master" ]
  pull_request:
    branches: [ "smart-contract-master" ]

jobs:
  build:
  
    runs-on: shibatoken/shibaswap

    steps:
    - uses: actions/checkout
    - name: Build the site in the jekyll/builder container
      run: |p
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
LICENSE:none
